### ISSUE TITLE
Not working on different languages

### ISSUE THREAD

**Issue by iveusss** [elcoreman/SpotifyAdsMuterExtention#1]
It's not working on different languages, because the aria-label on each language is different.
You should do -

    get isMuted() {
      const speaker = document.querySelector(this.speakerSelector);
      return (
        speaker?.getAttribute("class") &&
        speaker.getAttribute("class").split(" ", 1)[0].split("-")[2] == "off"
      );
    }

or 
        `speaker.getAttribute("class").split(" ", 1)[0].includes("off")`

or 
        `speaker.getAttribute("class").includes("off")`

**THIS DOES NOT LONGER WORK**

**Comment by iveusss** [comment]
New fix -
    speakerSelector:
      "#main > div > div.Root__top-container > div.Root__now-playing-bar > footer > div > div.now-playing-bar__right > div > div.volume-bar > button > svg > path",

    get isMuted() {
      const speaker = document.querySelector(this.speakerSelector);
      return (
        speaker?.getAttribute("d") &&
        speaker.getAttribute("d").includes == "M0"
      );
    }

**Comment by iveusss** [comment]
add new
```
this.speakerSvgSelector = props.speakerSvgSelector;
```

```
	speakerSvgSelector:
      "#main > div > div.Root__top-container > div.Root__now-playing-bar > footer > div > div.now-playing-bar__right > div > div.volume-bar > button > svg > path",
```

    get isMuted() {
      const speakerSvg = document.querySelector(this.speakerSvgSelector);
      return (
        speakerSvg?.getAttribute("d") &&
        speakerSvg.getAttribute("d").includes("L12")
      );
    }

**Comment by elcoreman** [comment]
Yes you right, I checked and set isMuted to be checked by SVG path as you suggested, Thank you!
